fix: change binary serilization type to byte[]
EasyMicroservices/Serialization pull request #18
Opened 2022-12-28 19:38 UTC by alighodrati

change type because of MessagePack Use             ReadOnlySequence<T>

2022-12-28 19:48 UTC, mahdidelzendeh72 approved these changes
Thanks @alighodrati

2022-12-29 08:10 UTC, Ali-YousefiTelori requested changes
Please check the request changes.

2022-12-29 08:10 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.Serialization.BinaryGo/Providers/BinaryGoProvider.cs
> +        public override T Deserialize<T>(byte[] value)
Please don't change the engine structure.
you can change only the message pack provider to return as ReadOnlySpan

2022-12-30 18:16 UTC, alighodrati commented
@Ali-YousefiTelori @mahdidelzendeh72 review pls

2022-12-30 18:58 UTC, Ali-YousefiTelori approved these changes
Thanks for your contributions @alighodrati

2022-12-31 13:08 UTC, mahdidelzendeh72 approved these changes
Thank for Contribute

2022-12-31 13:23 UTC, Ali-YousefiTelori approved these changes

2022-12-31 13:26 UTC, merged