add sample for how to use message package
EasyMicroservices/Serialization pull request #43
Opened 2023-01-08 19:47 UTC by sabababaei

## Description

### Related issue(s)
#39 

### Checklist:

- [ ] It refers to an [Issue](https://github.com/EasyMicroservices/FileManager/issues).
- [ ] It fixes a bug.
- [ ] It's a new feature (non-breaking change which adds functionality)
- [ ] It's a breaking (fix or feature that would cause existing functionality to change)
- [ ] My code follows the code style of this project.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] CHANGELOG is updated.
- [ ] Related language label is selected.

2023-01-09 07:55 UTC, Ali-YousefiTelori requested changes
@sabababaei.
Please remove the sample from the main sln

2023-01-09 07:55 UTC, Ali-YousefiTelori commented on src/CSharp/EasyMicroservices.Serialization.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WebAPISampleProject", "..\..\Samples\CSharp\ASPCore\WebAPISampleProject\WebAPISampleProject.csproj", "{26153456-D170-4B25-B183-DCFCE1207846}"
For the samples, the main solution doesn't have to change.

2023-01-09 08:10 UTC, Mohsen-Yaghoubi approved these changes

2023-01-09 08:19 UTC, Mohsen-Yaghoubi approved these changes

2023-01-10 12:01 UTC, Ali-YousefiTelori approved these changes

2023-01-10 12:03 UTC, mahdidelzendeh72 approved these changes

2023-01-10 12:04 UTC, merged